### ISSUE TITLE
Twitter handle

### ISSUE THREAD

**Issue by melvin0008** [CityOfZion/website#44]
The twitter handle mentioned on the website https://twitter.com/cityofzion_neo
seems to be outdated.

This is the new one.
 https://twitter.com/coz_official

Let me know if this is true. 

If it is I dont mind sending a PR

**Comment by metachris** [comment]
Hi, yes that's true, and a PR was just merged. Thanks for taking a look and opening this issue! Please do so again if you spot anything else.
